server:
  port: 8084

spring:
  datasource:
    username: username
    password: userpassword
    url: jdbc:mysql://url
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    prefix:
      classpath: /templates/
  mvc:
    static-path-pattern: /**
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  config:
    classpath: log4j2.xml
  level:
    com:
      example:
        mapper: debug

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.chen17.domain


