server:
  port: 8080

spring:
  datasource:
    username: root
    password: 19980413.com
    url: jdbc:mysql://localhost:3306/azc_zb_exist_error_device?useUnicode=true&characterEncoding=utf-8&useSSL=true&
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
logging:
  config:
    classpath: log4j2_dev.xml
  level:
    com:
      example:
        mapper: debug


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.chen17.domain

